version: '3.8'

services:
  db:
    image: postgres:15
    container_name: task-engine-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_engine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - task-engine-net
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: task-engine-redis
    networks:
      - task-engine-net
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build: .
    container_name: task-engine-web
    environment:
      # Database & Redis
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/task_engine
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      
      # Notification System - Email (Gmail example)
      - EMAIL_BACKEND=smtp
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USE_TLS=true
      # - SMTP_USERNAME=your-email@gmail.com
      # - SMTP_PASSWORD=your-app-password
      # - FROM_EMAIL=your-email@gmail.com
      
      # Notification System - SMS (Twilio)
      # - TWILIO_ACCOUNT_SID=your-twilio-account-sid
      # - TWILIO_AUTH_TOKEN=your-twilio-auth-token
      # - TWILIO_FROM_NUMBER=+1234567890
      
      # Notification System - Telegram
      # - TELEGRAM_BOT_TOKEN=your-bot-token
      
      # Default notification recipients
      # - DEFAULT_NOTIFICATION_EMAIL=admin@example.com
      # - DEFAULT_NOTIFICATION_PHONE=+1234567890
      # - DEFAULT_NOTIFICATION_TELEGRAM_CHAT_ID=123456789
      
      # Desktop notifications
      - DESKTOP_NOTIFICATION_TIMEOUT=10
      - DESKTOP_APP_NAME=Task Engine
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - task-engine-net
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: task-engine-worker
    environment:
      # Database & Redis
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/task_engine
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEFAULT_EXECUTOR=direct
      
      # Notification System - Email (Gmail example)
      - EMAIL_BACKEND=smtp
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USE_TLS=true
      # - SMTP_USERNAME=your-email@gmail.com
      # - SMTP_PASSWORD=your-app-password
      # - FROM_EMAIL=your-email@gmail.com
      
      # Notification System - SMS (Twilio)
      # - TWILIO_ACCOUNT_SID=your-twilio-account-sid
      # - TWILIO_AUTH_TOKEN=your-twilio-auth-token
      # - TWILIO_FROM_NUMBER=+1234567890
      
      # Notification System - Telegram
      # - TELEGRAM_BOT_TOKEN=your-bot-token
      
      # Default notification recipients
      # - DEFAULT_NOTIFICATION_EMAIL=admin@example.com
      # - DEFAULT_NOTIFICATION_PHONE=+1234567890
      # - DEFAULT_NOTIFICATION_TELEGRAM_CHAT_ID=123456789
      
      # Desktop notifications
      - DESKTOP_NOTIFICATION_TIMEOUT=10
      - DESKTOP_APP_NAME=Task Engine
    volumes:
      - ./app:/app/app
      - task_venvs:/tmp/task_venvs
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - task-engine-net
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: task-engine-scheduler
    environment:
      # Database & Redis
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/task_engine
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      
      # Notification System - Email (Gmail example)
      - EMAIL_BACKEND=smtp
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USE_TLS=true
      # - SMTP_USERNAME=your-email@gmail.com
      # - SMTP_PASSWORD=your-app-password
      # - FROM_EMAIL=your-email@gmail.com
      
      # Notification System - SMS (Twilio)
      # - TWILIO_ACCOUNT_SID=your-twilio-account-sid
      # - TWILIO_AUTH_TOKEN=your-twilio-auth-token
      # - TWILIO_FROM_NUMBER=+1234567890
      
      # Notification System - Telegram
      - TELEGRAM_BOT_TOKEN=7780519301:AAE_nD6gBWzv2eh7-8zkWgbAa56caHRncnU

      
      # Default notification recipients
      # - DEFAULT_NOTIFICATION_EMAIL=admin@example.com
      # - DEFAULT_NOTIFICATION_PHONE=+1234567890
      # - DEFAULT_NOTIFICATION_TELEGRAM_CHAT_ID=123456789
      
      # Desktop notifications
      - DESKTOP_NOTIFICATION_TIMEOUT=10
      - DESKTOP_APP_NAME=Task Engine
    volumes:
      - ./app:/app/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - task-engine-net
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    restart: unless-stopped

  flower:
    build:
      context: .
      dockerfile: Dockerfile.flower
    container_name: task-engine-flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - task-engine-net
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  task_venvs:
    driver: local

networks:
  task-engine-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: task-engine-br
